# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.xiaocai.name
date_format: "ordinal"
title: cmxiaocai.github.io
subtitle: "xiaoCai Blog"
description: "xiaocai的个人博客"
keywords: xiaocai
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: cmxiaocai
organization: xiaocai.name
organization_url: http://www.xiaocai.name
github_username: cmxiaocai
location: fuzhou, China
email: cmxiaocai@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: cmxiaocai
    repo: xiaocai-blog-comments
    oauth:
        client_id: 53bb4d7dc2e6975d345d
        client_secret: e0d0fcf4b268096b1a7f22d37948802769de466b
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: cmxiaocai
    repo: xiaocai-blog-comments
    clientID: 53bb4d7dc2e6975d345d
    clientSecret: e0d0fcf4b268096b1a7f22d37948802769de466b
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-2
