# Site settings
title: XiaoCai Blog
description: xiaocai的博客
email: cmxiaocai@163.com
baseurl: 
url: "http://www.xiaocai.name" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username: 
#twitter
twitter_username: 
github_username:  cmxiaocai

#linkedin
linkedin_username: cmxiaocai

#google analytics
google_analytics_id : 
#gplus
gplus_username: 

#fb_username
fb_username: pranav.tayberrycreative

#permalink /blog/2014/11/11/this-is-a-sample-post
<<<<<<< HEAD
permalink: /blog/:year:month:day/:title
=======
permalink: /blog/:year-:month-:day/:title
>>>>>>> 309d70c93088dee9068e511d816740681b6d81b9
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: maangalabscom
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  cmxiaocai:
    display_name: xiaocai
    email: cmxiaocai@gmail.com
    fb: 
    linkedin: 
    twitter: 
    github: cmxiaocai
